#!/opt/zenoss/bin/python
import sys
import commands

output = ""
command = 'snmpwalk -Cc -c %s -v1 %s:%s .1.3.6.1.4.1.2620.500.9002.1' % ('qbapub', '192.168.10.19', 161)
table = commands.getoutput(command).split('\n')
ile = len(table)/12
print len(table)
print ile
for i in range(0, 33):
	output = output + '\n'
        for j in range(0, 12):
        	output = output + table[i+j*ile] + "\n"
f1=open('/tmp/testfile', 'w+')
f1.write(output)
#print output

